HSA_model:
  opp:
    modality_indices: [0, 9, 18, 27, 36, 45, 61, 77]
    dff: 512
    d_model: 64
    num_heads: 4
    dropout_rate: 0.1
  
  pamap2:
    modality_indices: [0, 6, 12, 18]
    dff: 256
    d_model: 64
    num_heads: 4
    dropout_rate: 0.2
    
  daphnet:
    modality_indices: [0, 3, 6, 9]
    dff: 256
    d_model: 64
    num_heads: 8
    dropout_rate: 0.2
    
  skoda:
    modality_indices: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57]
    dff: 256
    d_model: 64
    num_heads: 4
    dropout_rate: 0.2
    
  uschad:
    modality_indices: [0,6]
    dff: 1024
    d_model: 128
    num_heads: 4
    dropout_rate: 0.1

  modality_indices:
    opp: [0, 9, 18, 27, 36, 45, 61, 77]
    mex: [0, 3, 6]
    mhealth: [0,3,12,21]
    pamap2: [0, 6, 12, 18]
    realdisp: [0, 13, 26, 39, 52, 65, 78, 91, 104, 117]
    daphnet: [0, 3, 6, 9]
    skoda: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57]
    uschad: [0,6]

train:
  batch_size: 64
  epochs: 100
  val_split: 0.1
  learning_rate: 0.001

test:
  batch_size: 64
