HSA_model:
  modality_indices:
    opp: [0, 9, 18, 27, 36, 45, 61, 77]
    mex: [0, 3, 6]
  dff: 512
  d_model: 64
  num_heads: 4
  dropout: 0.2

train:
  batch_size: 64
  epochs: 100
  val_split: 0.1