data_dir:
  raw: data/raw
  processed: data/processed

data_src:
  opp: https://archive.ics.uci.edu/ml/machine-learning-databases/00226/OpportunityUCIDataset.zip
  pamap2: https://archive.ics.uci.edu/ml/machine-learning-databases/00231/PAMAP2_Dataset.zip
  skoda: http://har-dataset.org/lib/exe/fetch.php?media=wiki:dataset:skodaminicp:skodaminicp_2015_08.zip
  uschad: http://sipi.usc.edu/had/USC-HAD.zip
  daphnet: https://archive.ics.uci.edu/ml/machine-learning-databases/00245/dataset_fog_release.zip

data_dest:
  opp: opp.zip
  pamap2: pamap2.zip
  skoda: skoda.zip
  uschad: USC-HAD.zip
  daphnet: Daphnet.zip

  
opp_preprocess:
  file_list: ['S1-ADL1.dat', 'S1-ADL2.dat', 'S1-ADL3.dat', 'S1-ADL4.dat', 'S1-ADL5.dat',
             'S2-ADL1.dat', 'S2-ADL2.dat', 'S2-ADL3.dat', 'S2-ADL4.dat', 'S2-ADL5.dat',
             'S3-ADL1.dat', 'S3-ADL2.dat', 'S3-ADL3.dat', 'S3-ADL4.dat', 'S3-ADL5.dat', 
             'S4-ADL1.dat', 'S4-ADL2.dat', 'S4-ADL3.dat', 'S4-ADL4.dat', 'S4-ADL5.dat']
  columns_list: [38,  39,  40,  41,  42,  43,  44,  45,  46,  51,  52,  53,  54,
            55,  56,  57,  58,  59,  64,  65,  66,  67,  68,  69,  70,  71,
            72,  77,  78,  79,  80,  81,  82,  83,  84,  85,  90,  91,  92,
            93,  94,  95,  96,  97,  98, 103, 104, 105, 106, 107, 108, 109,
           110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
           123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 244, 245, 250]
  sliding_win_len: 300
  sliding_win_stride: 150
  n_window: 15
  n_timestep: 20
  NOVEL_CLASSES: [2, 4]
  hi_label_to_id: {'0': 0, '101': 1, '102': 2, '103': 3, '104': 4, '105': 5}
  loco_label_to_id: {'0': 0, '1': 1, '2': 2, '4': 3, '5': 4}
  mid_label_to_id: {'0': 0, '406516': 1, '406517': 2, '404516': 3, '404517': 4, '406520': 5, '404520': 6, '406505': 7, '404505': 8, '406519': 9, '404519': 10, '406511': 11, '404511': 12, '406508': 13, '404508': 14, '408512': 15, '407521': 16, '405506': 17}

    
daphnet_preprocess:
    data_dir: 'data/processed/clean_daphnet_data.csv'
    feature_list: ['Ankle_acc_x', 'Ankle_acc_y', 'Ankle_acc_z', 'Thigh_acc_x','Thigh_acc_y', 'Thigh_acc_z', 'Trunk_acc_x', 'Trunk_acc_y','Trunk_acc_z']
    label_column: 'Label'
    benchmark_test_sub: 2
    benchmark_val_sub: 9
    sliding_win_len: 320
    sliding_win_stride: 160
    n_window: 10
    n_timestep: 32
    
uschad_preprocess:
    feature_list: ['acc_x', 'acc_y', 'acc_z', 'gyr_x', 'gyr_y', 'gyr_z']
    sliding_win_len: 200
    sliding_win_stride: 100
    n_window: 10
    n_timestep: 20

pamap2_preprocess:
  label_to_id: {'1': 0, '2': 1, '3': 2, '4': 3, '5': 4, '6': 5, '7': 6, '9': 7, '10': 8, '11': 9, '12': 10,
   '13': 11, '16': 12, '17': 13, '18': 14, '19': 15, '20': 16, '24': 17}
  columns_list: [1, 4, 5, 6, 10, 11, 12, 21, 22, 23, 27, 28, 29, 38, 39, 40, 44, 45, 46]
  file_list: {'train': ['subject101.dat', 'subject102.dat','subject103.dat','subject104.dat', 'subject105.dat', 'subject107.dat', 'subject108.dat', 'subject109.dat'],
            'validation': [],
            'test': ['subject106.dat']}
  sliding_win_len: 1500
  sliding_win_stride: 500
  n_window: 15
  n_timestep: 100
  NOVEL_CLASSES: [2, 6, 11, 14]

skoda_preprocess:
  sliding_win_len: 715
  sliding_win_stride: 245
  n_window: 13
  n_timestep: 55
